### ISSUE TITLE
Cannot read property 'lookup' of undefined

### ISSUE THREAD

**Issue by mrinterweb** [genkgo/ember-localforage-adapter#23]
I am trying to get ember-localforage-adapter working with ember-cli 0.2.0. I upgraded to ember-data 1.0.0-beta.16. Anytime I try to access `this.emberSync.find('modelName', 1)`, I encounter this error.

I first tried installing as described in the README. Then I tried http://stackoverflow.com/a/24331685/133998. Both ways I have tried, lead to this error. 

```
TypeError: Cannot read property 'lookup' of undefined
    at ember$data$lib$system$serializer$$default.extend.transformFor (http://localhost:5000/assets/vendor.js:68222:39)
    at applyTransform (http://localhost:5000/assets/vendor.js:67257:32)
    at http://localhost:5000/assets/vendor.js:73911:20
    at Map.forEach.cb (http://localhost:5000/assets/vendor.js:23590:13)
    at OrderedSet.forEach (http://localhost:5000/assets/vendor.js:23381:13)
    at Map.forEach (http://localhost:5000/assets/vendor.js:23594:19)
    at Function.ember$data$lib$system$model$model$$default.reopenClass.eachTransformedAttribute (http://localhost:5000/assets/vendor.js:73910:84)
    at ember$data$lib$system$serializer$$default.extend.applyTransforms (http://localhost:5000/assets/vendor.js:67254:14)
    at ember$data$lib$serializers$json$serializer$$default.extend.normalize (http://localhost:5000/assets/vendor.js:68401:14)
    at superFunction [as _super] (http://localhost:5000/assets/vendor.js:23784:22)
```

It looks like the application adapter is not available. I am running out of ideas.

**Comment by mrinterweb** [comment]
Oh WOW! I'm tired. I posted an issue on the wrong project :tired_face: This was supposed to be for ember-localstorage-adapter. Please disregard this. I was trying ember-localforage-adapter as well. I just had this tab open still. Sorry.

**Comment by frederikbosch** [comment]
@mrinterweb Go to bed then! No problem, get some rest!
