### ISSUE TITLE
Travis failed on `ember-113-compat`

### ISSUE THREAD

**Issue by sebweaver** [genkgo/ember-localforage-adapter#58]
As mentioned [here](https://github.com/genkgo/ember-localforage-adapter/issues/57#issuecomment-169719306) travis failed on building the branch `ember-113-compat`.

It seems to be related to some babel dependency issue:

```
Build failed.
File: dummy/adapters/application.js
Unknown option: sourceMaps
ReferenceError: Unknown option: sourceMaps
    at File.normalizeOptions (/home/travis/build/genkgo/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/home/travis/build/genkgo/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/home/travis/build/genkgo/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at Babel.transform (/home/travis/build/genkgo/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:24:21)
    at Babel.processString (/home/travis/build/genkgo/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:32:15)
    at Babel.Filter.processFile (/home/travis/build/genkgo/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-filter/index.js:136:31)
    at Promise.resolve.then.catch.err.file (/home/travis/build/genkgo/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-filter/index.js:85:21)
    at lib$rsvp$$internal$$tryCatch (/home/travis/build/genkgo/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/travis/build/genkgo/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:505:17)
    at /home/travis/build/genkgo/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1001:13
The command "node_modules/.bin/ember test" exited with 1.
```

From https://travis-ci.org/genkgo/ember-localforage-adapter#L456-L471

**Comment by frederikbosch** [comment]
Fixed by PR #65 .
